// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qwduvdxzlhotmbfhmctj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3ZHV2ZHh6bGhvdG1iZmhtY3RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDI0NDgsImV4cCI6MjA2NzkxODQ0OH0.6lSJVBABpOAXyBntCyXWSQeM4T8nyt82YL8uwAZ62pE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});